### ISSUE TITLE
Breaking rainmeter

### ISSUE THREAD

**Issue by ArcticDroid** [Kapiainen/Lauhdutin#1]
When I add this skin to rainmeter and launch the program fails to run correctly seemingly caught in some loop using roughly 30% of the cpu constantly. Sorry I don't have any more useful info.

**Comment by Kapiainen** [comment]
Where are the skin's files located?

The skin is set up to rebuild itself whenever certain user settings have changed. This behavior requires that the settings used in the previous rebuilding process can be written to a file (Variables.inc in this case) so that the values can be compared in the future. However, if the skin cannot write these values to a file, which may be the case if e.g. Rainmeter does not have the requisite permissions, then an infinite loop can occur. My guess would be that this is what is happening.

**Comment by ArcticDroid** [comment]
The files are located under C:\Users\UserName\Documents\Rainmeter\Skins

The program is set to launch as administrator, as soon as I load "Main.ini" the program freezes up and only resumes to work after the files have been removed from the folder. When I remove the files Rainmeter gives me an error message saying "Unable to refresh skin "Lauhdutin\lauhdutin\Main.ini": File not found.". Dunno if any of that it of any help, thanks for the help.

**Comment by apoapostolov** [comment]
I am having the same issue on Windows 10. Rainmeter simply freezes and has to be killed.

**Comment by Kapiainen** [comment]
Where is the *Skins* folder located?

**Comment by Atynine** [comment]
Can be solved by #4
