### ISSUE TITLE
The launcher stop working on every PC i have it installed after the latest steam update 

### ISSUE THREAD

**Issue by Xarishark** [Kapiainen/Lauhdutin#10]
It says no games found on all of the terminals and even if i remove the steamID or folderpath the same error persists I think your detection is out of date can you please check it out when you can?

**Comment by rig0** [comment]
My launcher is also not detecting any of the games except for the non-steam games I've added. The latest steam update must've broke something.

**Comment by Xarishark** [comment]
lets hope he fixes it :/

**Comment by Cyb3rzombie** [comment]
Found the error. At least for me it worked. If you check the file located in "(SteamDirectory)\userdata\(userID)\7\remote\sharedconfig.vdf" you will find a key "Apps". In my case it started with a capital letter and that was the exact problem since the script was searching for "apps". So simply changed the line 275 in the Lua script 
tSharedConfigApps = RecursiveTableSearch(tSharedConfigApps, S_VDF_KEY_STEAM)[S_VDF_KEY_APPS]
to 
tSharedConfigApps = RecursiveTableSearch(tSharedConfigApps, S_VDF_KEY_STEAM)["Apps"]

Hope it helps.

Note: This is should be only temporary until the author fixed it.

**Comment by Xarishark** [comment]
Will try it and report back

**Comment by Xarishark** [comment]
OMG I FUCKING LOVE YOU (FIXED)

**Comment by Xarishark** [comment]
Ok os i forked and created a file fix request so he can just accept it to fix it and he doesn't have to bother( Im pretty new to github so sry if I fucked up). I gave you credit for your fix ofc!

**Comment by Cyb3rzombie** [comment]
Glad I could help.
Well it's my first post here so I am also pretty new.

**Comment by rig0** [comment]
Thank you it worked! By the way a more permanent fix would be to go into Lauhdutin.lua and on line 59 change: 

S_VDF_KEY_APPS = 'apps' 
to 
S_VDF_KEY_APPS = 'Apps'

**Comment by rig0** [comment]
That's strange. Mine is still working. The original is not.

**Comment by Cyb3rzombie** [comment]
Search in the files "(SteamDirectory)\userdata\(userID)\config\localconfig.vdf" and "(SteamDirectory)\userdata(userID)\7\remote\sharedconfig.vdf" for "apps". In my case it was written in the localconfig.vdf in small letters and in the sharedconfig.vdf in capital letters.
That's why I didn't change the S_VDF_KEY_APPS to 'Apps' since it wouldn't work anymore (at least for my case). Iit was meant for a temporary fix only but you are right that this would be the better way.

You can check for both cases like this
Add another variable directly under S_VDF_KEY_APPS and call it for example S_VDF_KEY_APPS_SMALL_LETTERS = 'apps'

Then add the if statement directly under the this line:
tSharedConfigApps = RecursiveTableSearch(tSharedConfigApps, S_VDF_KEY_STEAM)[S_VDF_KEY_APPS]
if tSharedConfigApps == nil then
tSharedConfigApps = RecursiveTableSearch(tSharedConfigApps, S_VDF_KEY_STEAM)[S_VDF_KEY_APPS_SMALL_LETTERS]
end

**Comment by Fraali** [comment]
To whomever is still looking into this, Steam changed a variable from apps to Apps in the LOCALconfig.vdf only with an update. (Why did they even change it) 

To fix this, add " S_VDF_KEY_APPS_BIG = 'Apps' " at line 59/60.
Then at line 273/274, change the [S_VDF_KEY_APPS] to [S_VDF_KEY_APPS_BIG]. 

Make sure the one you change is on the line with the LOCAL config apps, not the SHARED config apps as that will screw things up.

**Comment by Kapiainen** [comment]
The [vdf-update](https://github.com/Kapiainen/Lauhdutin/tree/vdf-update) branch has an updated version of the Lua script, which should hopefully be able to handle any VDF file by converting all keys to lower case. The global variables, which are used when accessing stuff in tables, have also been converted to lower case. These changes will hopefully be future proof and work for anyone regardless of when their VDF files were created and which case the keys are in.

**Comment by Xarishark** [comment]
Ty for the update it also now fixed some games that would not load into the launcher ty man

**Comment by Kavex** [comment]
Yeah the  vdf-update branch fixed the issue. I'm not sure if you are still working on vdf-update branch. master branch still has the own Lauhdutin.lua file.
