### ISSUE TITLE
Manually add uninstalled games

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#108]
I was thinking that could be great to have the option to manually add an entry for uninstalled games on shortcuts platform. 

The way I thought is to manually create an entry in the database with the name of the game and the platform (override or standard shortcut), and put a banner in their folder. Then when you install that game, you can rename the shortcut to the name you put in that entry, or simply remove the previous entry.

With this at least you can have track all games of a unsupported platform, even if you didn't install them.

**Comment by Kapiainen** [comment]
I'm not sure. I could e.g. change the shortcut detection to set the game as uninstalled, if the path it is pointing at is no longer valid. You could then create a shortcut, which points at e.g. an empty text file (Windows complains if the shortcut does not have a valid path), and then delete the text file after the shortcut has been created. Anything beyond that (e.g. a menu of its own) would have to wait until after version 3.0.0 is finished and out of beta.

**Comment by BanCrash** [comment]
Sounds well enough! I don't have any trouble on wait for that. Thanks!

**Comment by Kapiainen** [comment]
I've pushed commits to implement a new platform and menu so that games can be added manually via a custom skin action called `Add a game`. It is possible to input the title, path, and whether or not the game is currently installed. One can then use the *Game* menu to edit the game's properties further (e.g. platform override, path, hours played, whether or not it is installed). I kept the new menu as simple as possible and left the ability to edit other properties to the *Game* menu.

I still need to implement a page for the settings for toggling the platform and defining its starting/stopping bangs.

**Comment by BanCrash** [comment]
Thanks for your work! I am testing it and I have a little issue. I set the game to Origin platform, and when filtering, the skin says "3 games". But when I click, only appears 2 games, being missing the custom game. And if I select "not in platform X -> Origin" appears that custom game. Shouldn't be on Origin too?

Except that seems to work great! Thanks you!!

**Comment by Kapiainen** [comment]
Are some of those games Windows shortcuts that are placed in a subfolder called *Origin* and the rest added via the new menu?

**Comment by BanCrash** [comment]
That's correct, the 2 games that are appearing are from Origin subfolder, and the game that aren't appearing is added by the new menu.

**Comment by Kapiainen** [comment]
Good. I'm quite certain that I know what needs to be fixed in that case.

**Comment by BanCrash** [comment]
Perfect! Feel free to ask for whatever you may need.

**Comment by Kapiainen** [comment]
Should be fixed in the commit that I just pushed.

**Comment by BanCrash** [comment]
I just tried and works perfect now. Thanks you, nice job!
