### ISSUE TITLE
"Setting the Steam path does not always succeed in updating the list of accounts."

### ISSUE THREAD

**Issue by SirUseless1** [Kapiainen/Lauhdutin#109]
Yeah its a known Issue. I can't choose my Account.
I tested 3.0 Beta 4 and 2.71

Is there are workaround or something to fix it?

**Comment by Kapiainen** [comment]
One person reported that adding `/` to the end of the path fixed it, but I'm having no issues with just `D:/Programs/Steam`.

**Comment by SirUseless1** [comment]
Thanks, but didn't work :/

**Comment by BanCrash** [comment]
Did you have non-english characters on you nickname? I make a test naming my profile with "á" and can't choose it. I get back to "a" and works perfect again.

**Comment by jetjaguar** [comment]
I hit this problem while installing Beta 3.0.0 v7 and discovered that due to my path having a space in it (e.g. F:\<user>\My Documents\Rainmeter\Skins\Lauhdutin.-.3.0.0.beta.7\) most of the bat files would have trouble parsing "My Documents" and often split up the path as two separate files.

Modifying the offending .bat files (@Resources\settings\platforms\steam\listUsers.bat, @Resources\main\platforms\battlenet\identifyFolders.bat) to "sanitize" the paths with "%variable%" (vs. %variable%) allowed my username to show up or my library to be scanned.

listUsers.bat---------------
11 dir %1 /b /o:n /a:d > "%users%"
12 echo "" > "%completed%"

I don't quite see everything working (may or may not be related to this change), just something I noticed that will hopefully help with a fix

**Comment by Kapiainen** [comment]
I went through all of the batch files and added quotation marks to the various variable declarations for paths. The issues related to whitespace in paths should hopefully be fixed now in beta 8.

**Comment by Kapiainen** [comment]
@jetjaguar, I went through all of the batch files and added quotation marks to the various variable declarations for paths. The issues related to whitespace in paths should hopefully be fixed now in beta 8.
