### ISSUE TITLE
Gives me an error when i try to use with steam :/

### ISSUE THREAD

**Issue by ketchup4eto** [Kapiainen/Lauhdutin#111]
## Short description of the issue
Well, today I installed Rainmeter and decided to play a bit with it and when i tried to install Lauhdutin it would give me an error.

## Lauhdutin version
3.0.0 beta 5

## Rainmeter version
4.2 Beta Release

## Python version
3.6.4

## Windows version
Windows 10

## Error messages
(https://user-images.githubusercontent.com/29573973/37867353-bcf4a59a-2f9f-11e8-914e-2fd759640d6b.png)

http://prntscr.com/ivtuah Error: utility.lua:476: ''parseVDF'' encountered unexpected input on line 1: 
[Rainmeter.log](https://github.com/Kapiainen/Lauhdutin/files/1844709/Rainmeter.log)

**Comment by Kapiainen** [comment]
I've uploaded a new version with some additional log messages, which will hopefully help troubleshoot the issue. Could you install the new version and try enabling the `Log` setting in the skin's settings? The skin should now print a bunch of information in Rainmeter's log (found in Rainmeter's `About` window). Could you post a screenshot of the log just prior to the error?

My initial assumption was that the issue was caused by an empty `appmanifest_*.acf` file (each game has one) left behind by Steam when you uninstalled a game, but I haven't been able to replicate the issue based on that assumption. The new version should help to narrow down the issue, if it is caused by a specific game's appmanifest. The skin also uses the VDF parser for a few other files and if one of those other files is causing the issue, then the log should help figure that out as well.

**Comment by ketchup4eto** [comment]
should.... but it didn't help much. I updated it to 3.0.0 beta 6 and now the only thing that comes up in the log is [this](https://pastebin.com/hWD0vyKq)

**Comment by Kapiainen** [comment]
Looks like the `Log` setting has not been enabled in the skin's settings.

**Comment by ketchup4eto** [comment]
Oops my bad... I forgot to turn it on after the update. [Log](https://pastebin.com/SsHwwNuh)

**Comment by Kapiainen** [comment]
It looks like `appmanifest_295110.acf`, the manifest for _Just Survive_, is the file that is causing the issue. It should be in `\Steam\steamapps` (or the `steamapps` folder in whichever Steam library it is installed). It should contain something along the lines of:

```
"AppState"
{
	"appid"		"295110"
	...
}
```
Replace `...` with more key-value pairs such as the name of the game, name of the folder where the game is installed, etc.

**Comment by ketchup4eto** [comment]
Thank you so much! It looked like the appmanifests of Just Survive and Dota 2 were corrupted. Managed to fix it by deleting them, steam will download them if needed. It works now :)

**Comment by Kapiainen** [comment]
Glad to hear that the issue has been resolved.
