### ISSUE TITLE
[QUESTION] Hours Played/Overwatch Banner

### ISSUE THREAD

**Issue by devjaa** [Kapiainen/Lauhdutin#115]
Is it possible to disable hours played or draw them from Steam directly? Also, my Overwatch Banner isn’t loading correctly, and I have tried reinstalling. Windows 10, Python 3.7.2, Rainmeter 4.1, not sure about lauhdutin but at least 3.0.0 1.

**Comment by Kapiainen** [comment]
> Is it possible to disable hours played or draw them from Steam directly?

What do you mean by directly? From the Steam client rather than your Steam community profile? If this is what you meant, then the latter is the only option as far as I know. Or did you mean something else?

> Also, my Overwatch Banner isn’t loading correctly, and I have tried reinstalling.

In what way is it not loading correctly? Blizzard's store pages have been updated quite a while ago and unfortunately that means that the skin can no longer automatically download banners for games installed via the Battle.net client.

**Comment by Kapiainen** [comment]
Version 3.1.0 (currently in alpha) will have a setting for what to show on the slot overlay and you can even disable all of the text.
