### ISSUE TITLE
!ShowMeter: [SkinEnabler] not found (Lauhdutin\Main.ini)

### ISSUE THREAD

**Issue by TrapStoner** [Kapiainen/Lauhdutin#148]
3.1.0-beta 4 wont even show up 
Rainmeter 4.2 final
Windows 10 Anniversary

http://prntscr.com/kbczgx

i think it has something to do with the new steam version and the parser because it wont find my account
http://prntscr.com/kbda3h

**Comment by Kapiainen** [comment]
For the issue with ``[SkinEnabler]` you should be able to fix it by forcing the skin to be rebuilt:
a) Open up the skin's settings, right-click somewhere on the settings window/config, and click "Rebuild main slots". Close the settings config and refresh the main config.

or

b) Adjust the number of rows/columns of slots, slot width, or slot height. Save and close the settings.

I apparently need to update which setting changes trigger a rebuild of the skin.

Regarding the issue with the account: Can you select your account via the skin's settings? Could you open up `\Skins\Lauhdutin\@Resources\settings.json` in a text editor (e.g. Notepad)? Look for `"accountID"`. You should see something like `"accountID": "0123456789"` where the numbers will be unique for your account, but the important things is that there should only be a bunch of numbers inside of the quotes. The error message (`The Steam account is invalid.`) is due to an attempt to verify that the account ID is indeed a number (i.e. does not contain any characters that are not numbers).

**Comment by TrapStoner** [comment]
Yes for the skin enabler i fixed it minutes after posting the issue. For the steam account one it just fixed itself after restarting the pc (my electicity went down)

**Comment by TrapStoner** [comment]
now it wont download all the banners

nvm i fixed this aswell it just wont auto download them

**Comment by danail23** [comment]
nvm i fixed this aswell it just wont auto download them

**Comment by Kapiainen** [comment]
What exactly do you mean when you say that it won't automatically download them?

Version 3.1.0 adds a setting for how often games should be detected, which is also when the skin downloads any missing banners that it can download. The setting defaults to once per day, but can be changed. You can also forcibly detect games at any time by right-clicking on the skin and clicking on `Detect games` in the `Custom skin actions` section of the context menu.

**Comment by TrapStoner** [comment]
well i meant that it wont download them when first setting up steam profile and reloading the skin. it detected all games and showed them but didnt download the banners for them. sorry for responding that late
