### ISSUE TITLE
Unable to launch added game

### ISSUE THREAD

**Issue by Dididoo12** [Kapiainen/Lauhdutin#158]
## Short description of the issue

Upon trying to launch an added game, I receive an error that will be listed below. Is there anything to keep in mind when filling out the "path" field in the "Add Game" menu? I am using an absolute file path ( "C:\\Program Files (x86)\\Minecraft Launcher\\MinecraftLauncher.exe" as found in games.json).

## Lauhdutin version

3.1.0 beta 4

## Rainmeter version

4.3 Final Release

## Windows version

Windows 10

## Error messages

[Displayed by skin]: settings.lua:763: attempt to index field 'custom' (a nil value)

## Steps to reproduce the issue

Added a new game using the "add game" menu, reloaded skin and clicked the game.

**Comment by BanCrash** [comment]
Hello, this is an issue with the skin, and there is nothing you can do to fix this without changing somethings on the code.

Do you use custom starting and / or stopping bangs instead general bangs? Because if not, because you don't have custom bangs or because you want to use general bangs, you can easily fix this changing two lines of code. But if you use them, you'll have to modify more lines.

Let me know if you want to use custom bangs instead general bangs or not and I'll help you fix this.

Regards.

**Comment by Dididoo12** [comment]
Hi, thanks for the reply! I don't use custom bangs; I don't think I messed with the bangs at all and instead used the "add custom game" option from right clicking the skin. Please let me know if there's anywhere to change those couple of lines, thanks! And as a heads up I'm out of town right now so I won't be able to try the fix immediately; I'll be back Aug. 30 though, so if something comes up even after applying the fix I'll reply back to this thread :)

**Comment by BanCrash** [comment]
Hello, perfect then. This is an issue present on the code, nothing of your fault.
 
For solving it replacing custom bangs with global bangs go to `skin folder -> @Resources -> shared -> settings.lua` and open it with a text editor.

Go to line 763 and replace `self.settings.platforms.custom.bangs.starting` with `self.settings.bangs.global.starting`

Go to line 777 and replace `self.settings.platforms.custom.bangs.stopping` with 
`self.settings.bangs.global.stopping `

Save and reload the skin and done, you shouldn't have more issues with this matter.

If some day you wanna have custom bangs then let me know and I'll give you a more complicated solution for them to work.

Regards.

**Comment by Dididoo12** [comment]
Hi, thanks for the reply! I got back from out of town and tried the fix, though clicking the game's rectangle still doesn't seem to launch anything. I looked at games.json and the custom game's section shows:

![image](https://user-images.githubusercontent.com/44324145/64067152-d6094780-cbf1-11e9-8b37-c98a77b0bdcd.png)

Here is the section where I applied the fix in settlings.lua: 
![image](https://user-images.githubusercontent.com/44324145/64067136-a2c6b880-cbf1-11e9-9e8f-8313f33d4aee.png)

If there is anything else I can show to help in finding the issue, please feel free to let me know!

**Comment by BanCrash** [comment]
Hello again.

This is other issue completely different, but more easy to solve.

When you manually add a game, please add double `\` (so `\\`) instead only one. Because `\` is an escape character on lua.

So, when you add a game, instead writing `C:\Program Files (x86)\` you have to write `C:\\Program Files (x86)\\`

Edit the path for that game taking this as consideration and your issue should be solved.

Regards.

**Comment by Dididoo12** [comment]
That makes complete sense, thanks so much! The issue is solved now. 

Best regards!

**Comment by BanCrash** [comment]
Glad you solved ;)
