### ISSUE TITLE
Steam integration broken after latest Steam client update

### ISSUE THREAD

**Issue by asshuka** [Kapiainen/Lauhdutin#168]
## Lauhdutin version
3.0.4

## Rainmeter version
4.5.12.3616

## Windows version
Windows 10 21H1

## Error messages
None

## Steps to reproduce the issue
Steam games simply are not displaying anymore after the latest client update, only Windows shortcuts. Neither refreshing or detecting games works. I've reinstalled Lauhdutin once, and am using @BanCrash 's quick fixes #166 
Curiously one game from Steam does show up, notably one I have a Windows shortcut for (custom executable).

![220314_232330](https://user-images.githubusercontent.com/80346620/158217772-f0423622-5341-4d1e-b2a6-f78acef38930.png)
![220314_232330 (2)](https://user-images.githubusercontent.com/80346620/158217735-793c0bad-4e62-4fb5-8ddf-f49b5d1e7696.png)

As you can see, this banner is pulled from Steam and not my Windows shortcut. This is the only banner Lauhdutin downloaded after the reinstall.

UPDATE: **This seems to only happen if you enable parsing community profile**. I disabled it and Lauhdutin are detecting Steam games again. I noticed Lauhdutin seemed to have detected the games twice though? The amount of banner files in /@Resources/cache/steam is half of what the UI said it downloaded. And the banners display twice on the skin of course.
![220314_232346](https://user-images.githubusercontent.com/80346620/158220449-b246cf2f-e9fd-4263-86c0-ae999d14393c.png)

**Comment by BanCrash** [comment]
Hi @asshuka , could you see if there is anything written to the log after detecting games with the parse community profile option enabled?

You can access Rainmeter log by right-clicking Rainmeter tray icon -> About -> Log.

**Comment by asshuka** [comment]
@BanCrash 
![220315_030332](https://user-images.githubusercontent.com/80346620/158256989-f367265b-fca7-49ff-9e4c-d3c5cd8186f1.png)
This would continue on for the rest of my Steam library.

**Comment by BanCrash** [comment]
Could be that your steam community profile or game details on your profile are hidden? You can check on your steam profile, clicking on edit and then Privacy settings.

**Comment by asshuka** [comment]
It is all public, the only things on private are my friends list and inventory.

**Comment by BanCrash** [comment]
> It is all public, the only things on private are my friends list and inventory.

Okay, I can't check this until Thursday, so let's this on hold until I see if it's something that is happening to me too.

**Comment by asshuka** [comment]
Update: it seems the latest Steam client update (package version 1647446817) fixed this issue.

**Comment by BanCrash** [comment]
@asshuka glad to read that, I was going to test it in a while so time saved haha.

**Comment by humanspida** [comment]
I've just started experiencing this issue myself... no steam game tiles
This only started for me in the last few days, cant be specific about exactly when but its very recent.
Havent made any changes to my settings between when it was working and when it stopped providing steam games

Nothing I've tried has restored them with "parse community profile" checked... as was mentioned above - unchecking it fixes the issue for me as well though...
I've tried the steam beta update and rolled it back... I've tried a complete reinstall of the skin and setting everything up fresh... I've re-downloaded the init lua file for steam that you made changes to and I forked, then replaced the original after the fresh install of the skin. My profile is public as well so that shouldnt be an issue but if I have "parse community profile" checked it wont load and include any steam games at all.

Can set the client path and it automatically detects my steam account name in the settings and then "detect games" gets the skin to detect all platforms and gives no errors, even for steam... just wont actually load any games or even blank tiles for steam games
while that "parse community profile" option is checked.

Built: Feb 13 2023
Steam API: v020
Steam package version: 1676336721

GoG games are provided with banners auto downloaded, Battle.Net games are provided (added the banners myself and that works), Windows shortcut for Star Citizen (banner added myself works)...

The steam games just aint being included as part of the skin at all for me anymore and there's no games to "unhide" and everything except the steam games being provided, visible, and able to be clicked/launched is working with "parse community profile" for steam checked 


I also get duplicate entries for things installed to the default client install location on the C drive - wallpaper engine, steamworks redistributable, and borderless gaming all are installed to the clients C drive install folder and all display themselves twice which is kinda weird but not really an issue once you hide 'em.
I think the duplicate banners might be something to do with installing to the default C drive location as NOTHING installed to a separate library location is giving me duplicates personally.

Guess I'll just uncheck "parse community profile" and carry on without - its not like that info is important to me, just a shame its borked now.

@BanCrash

**Comment by BanCrash** [comment]
@humanspida sorry to read that, it's been a while since this project has been abandoned and it's a matter of time that every integration is broken I'm afraid. About your issue, I can't help you since I switched to [Playnite](https://github.com/JosefNemec/Playnite) as game launcher. I suggest you to do the same, with that or another game launcher.

**Comment by humanspida** [comment]
dear lord that things fucking massive and hideous - might as well just use the individual clients with the design and look of that launcher as its basically no different to using a client anyway
completely defeats the point of having lauhdutin - to get away from having to open a damn client

Cant do it... having Lauhdutin embedded at the top of my desktop is the only way

As long as it can still launch games that will be enough for me - I dont care about the platform integration for information being shown at all

**Comment by BanCrash** [comment]
> dear lord that things fucking massive and hideous - might as well just use the individual clients with the design and look of that launcher
> 
> Cant do it... having Lauhdutin embedded at the top of my desktop is the only way
> 
> As long as it can still launch games that will be enough for me - I dont care about the platform integration for information being shown at all

Well, in that case I wish you that this launcher works a lot of time more.

**Comment by humanspida** [comment]
thats my hope as well... 
that any future updates to these gaming platforms either doesnt break anything except the profile info integration OR can be fixed with a small change to the skins backend to still acquire the games and be able to launch them.
I know sometimes they change how the platform handles games, etc - and that would potentially mean a change may be necessary to the skin to tell it how to get them with the new method.

Wouldnt it be awesome if Valve decided this is too good a thing to let die, and picked this awesome launcher up to make it an optional extra, while developing and maintaining a version of it themselves (without making too many changes to it).

I'd take it over and maintain it myself if I were capable of doing so but I lack the know-how to do this.

Pipe dreams are nice huh. lol
