### ISSUE TITLE
Steam games do not show up with v2.2.0 beta

### ISSUE THREAD

**Issue by tenzion** [Kapiainen/Lauhdutin#21]
Installed v2.2.0 beta1.
Steam games do not show up after this.
![image](https://cloud.githubusercontent.com/assets/1419242/22459392/b15bf30c-e7a0-11e6-990c-b2e536cd0075.png)
Furthermore, only the first 3 games of the Windows shortcuts show up, not the last two. File naming is correct (both banner and shortcut).

**Comment by Kapiainen** [comment]
Steam games are not showing up because the skin cannot find `\Steam\userdata\YOURUSERDATAIDHERE\7\remote\sharedconfig.vdf`. Either the Steam path is wrong, the UserDataID is wrong, or both settings are wrong.

Try renaming the last two Windows shortcuts so that they don't have the `.exe` part in their name.

**Comment by tenzion** [comment]
Sharedconfig.vdf was not there, correct.
I've enabled categories in Steam now which now created a sharedconfig.vdf file in said location. I've updated all settings and locations, but they do not turn up.

Removed the .exe in the shortcuts, but no difference though.

**Comment by Kapiainen** [comment]
Uploaded a new beta version to address the issue with a missing `sharedconfig.vdf`.

Is the Python terminal's output different now? Errors in Rainmeter's log?

**Comment by Kapiainen** [comment]
Try using version [2.2.0 Beta 3](https://github.com/Kapiainen/Lauhdutin/releases/tag/2.2.0beta3). The issue regarding Windows shortcuts should be fixed now.
