### ISSUE TITLE
I can't rebuild after updating

### ISSUE THREAD

**Issue by GlowMLG** [Kapiainen/Lauhdutin#28]
In the updating tutorial the last step is:

Load Settings.ini in Rainmeter, click Save, click Exit, right-click on the skin, go to Custom skin actions, and click on Rebuild.

But look:

https://youtu.be/W3HWSTRU5dU

I'm really sorry if it's a noob question

**Comment by Kapiainen** [comment]
You seem to running an old version of Lauhdutin (1.3.2 based on the video) with some files from a 2.x.x release mixed in. Updating is **only** supported if you were previously using version **2.0.0 or later**. If you were using an earlier version, such as 1.3.2 in your case, then you need to completely remove the old version and do a fresh install according to the steps described [here](https://github.com/Kapiainen/Lauhdutin#installing).

**Comment by GlowMLG** [comment]
Ahhh okay dude you're amazing you're so active! I love your skin ;D Cheers!!!!!!

**Comment by Kapiainen** [comment]
It would probably be best to set everything up from scratch. Version 2.0.0 was basically a complete rewrite of the skin and the old settings files are not supported. However, you can use the old Steam banners (copy them to `\Lauhdutin\@Resources\Banners\Steam`) rather than having to download them all again. The `Settings.ini` skin should make it easy to set everything up.

**Comment by GlowMLG** [comment]
Okay thank you very much

One last thing. It's stuck now at Initializing backend. What have I done wrong? I just deleted the Lauhdutin folder and put the new one, reloaded rainmeter and modified the settings

**Comment by Kapiainen** [comment]
You'll need Python 3.5 and there are some specific settings that you should have enabled when installing it. Check the [requirements](https://github.com/Kapiainen/Lauhdutin#requirements) section for the details.

**Comment by GlowMLG** [comment]
So I can't use it with python 3.6?

**Comment by Kapiainen** [comment]
You can, I'm using 3.6 myself.

**Comment by GlowMLG** [comment]
Ahh okay thanks. 

One last tip: you should make a video about how to installit. Just for stupid people like me. It'd help a lot hahaha

**Comment by GlowMLG** [comment]
Hey I'm sorry but I can' make it :/ I'm sure i also installed the tkinter and the path system thing but after rebooting and reinstalling it's still stuck...

I'm a noob sorry

**Comment by Kapiainen** [comment]
Is it still stuck on `Initializing backend...`? Any errors in Rainmeter's log? Try setting the Python path setting in the `Settings.ini` skin to `python` instead of `pythonw`. If the Python scripts are executed correctly, then you should see a terminal showing information about what is happening (e.g. parsing Steam files, downloading banners). If the terminal does not show up, then the value of the Python path setting is not correct. At that point you will either have to make sure that Python was added to Windows' PATH system variable or use the absolute path to the Python executable (e.g. `C:\Program Files\Python\python.exe`).

**Comment by GlowMLG** [comment]
Thanks for your help, It's working now

You deserve the best developer award of 2017

**Comment by GlowMLG** [comment]
Hey there, again.
I can't manage to show more than 1 game

https://youtu.be/hS8qm-clFkk

**Comment by Kapiainen** [comment]
The video is set to be private.

**Comment by GlowMLG** [comment]
Okay sorry its fixed now

**Comment by Kapiainen** [comment]
Have you tried rebuilding the skin? Right-click on the skin, go to *Custom skin actions*, and left-click on *Rebuild skin*. The skin should automatically be rebuilt whenever you change e.g. the dimensions of a slot or the number of slots, save, and then exit.

**Comment by GlowMLG** [comment]
AHHHHHHH Okay 

I was using an old version so I didnt know it hahah Thanks!!!!

**Comment by GlowMLG** [comment]
Aand how do I delete a shortcut from steam without uninstalling it from steam? I only find the banners

**Comment by Kapiainen** [comment]
I'm not sure I understand correctly what you are saying in the first paragraph. Could you explain what you mean? If you want to hide a game in Lauhdutin, then you can right-click on the skin, go to **Custom skin actions**, and left-click on **Toggle hide game**. Any game you click on, until you repeat the steps in the previous sentence, will be hidden. You can choose the **Toggle unhide game** option to show the list of hidden games, and make a game visible again.

Folders are not currently supported.

**Comment by GlowMLG** [comment]
Okay first problem solved

And well I'll wait ;D

Thanks for the help, seriously

**Comment by Kapiainen** [comment]
Version 2.6.0 (currently in alpha) includes a fix for the issue with using shortcuts to folders.

**Comment by GlowMLG** [comment]
Thanks! Gonna download it :)
