### ISSUE TITLE
[QUESTION] How to delete updates of time?

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#35]
Hello. I have many games in Steam that I have run on idle, so I have many extra hours that I want to erase. I want this skin only gets the time from Steam the first time the game is added, and then count the hours with the own counter of this skin, to be easy edited the info about the time. Is there is anyway to do that right now?

I tried with editing the time on games.json but the next time I update the skin it downloads again the correct time.
I'm using the last beta and the last release of phyton.

Thanks for the skin by the way, it is very complete!!

**Comment by Kapiainen** [comment]
If you set the `Steam profile` setting to `Ignore`, then the skin won't parse your Steam community profile for the total hours played and then you are free to edit the values. However, this does mean that some functionality, which may not be important to you, stops working (e.g. being able to list games you do not have installed). If you ever set the setting back to `Parse`, then your edited values will be overwritten.

Other options would be to edit `\Lauhdutin\@Resource\Backend\GetGames.py` (lines 165-168) or `\Lauhdutin\@Resource\Backend\Steam.py` (lines 310-311) so that either your edited values take precedence or the values for total hours played from the community profile are ignored, respectively. You would have to modify these files whenever you install/update Lauhdutin. The line numbers are based on [this version of `GetGames.py`](https://github.com/Kapiainen/Lauhdutin/blob/ff586ddac3b29807ac75d8163d85428c377e1d26/Lauhdutin/%40Resources/Backend/GetGames.py) and [this version of `Steam.py`](https://github.com/Kapiainen/Lauhdutin/blob/21939d33e43b185e50783809834a367ab17b469a/Lauhdutin/%40Resources/Backend/Steam.py).

There are advantages and disadvantages to either approach so you'll have to figure out which suits you better.

**Comment by BanCrash** [comment]
Thanks for the answer, I will check it!

Other question, there is a way to show both installed and no installed games? I tried somethings but I can't get it to work.

**Comment by Kapiainen** [comment]
That is not currently supported.

**Comment by BanCrash** [comment]
Understood, thanks for the fast answers and for the idea!!
