### ISSUE TITLE
(Suggestion) Add Origin & Uplay

### ISSUE THREAD

**Issue by LinusHe** [Kapiainen/Lauhdutin#63]
I do not know if it would work, but It would be pretty nice if origin and uplay could be supported :)

**Comment by Kapiainen** [comment]
I've looked into implementing support for Origin in the past, but it doesn't seem very likely to happen. As far as I know there is no public API. Locally stored files that appear relevant are encrypted and I'd rather not mess with anything that might expose any sensitive information.

Blizzard App/Battle.net support is similar to Origin in that regard, but with two crucial differences: there are far fewer games and most of them can be installed for free. Hence why the support for Blizzard App/Battle.net has uses hardcoded data rather than processing e.g. locally stored files and databases.

I would not be able to properly implement nor maintain support for Uplay as I do not have the client installed on my computer and I do not have an account nor will I in the future.

For the moment you will have to make do with manually placing shortcuts to games from those platforms in the appropriate folder (i.e. `\Lauhdutin\@Resources\Shortcuts`).

**Comment by LinusHe** [comment]
Thank you for your answer.

I didnt know, that its possible to create own shortcuts. I have created them now for my origin / uplay games :)
