### ISSUE TITLE
Issues with animations

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#70]
Hello again, I found that if Zoom In hover animation is enabled, when you hide a game the banner still appearing until you stop on hover it. With jiggle that doesn't happen, or with that option disabled.

Other issue, shake hover animation is not working I think, at least I don't see any change in the banner.

And finally, in Zoom in hover animation I don't know if this a bug or it works like it has to work, I don't see much problem with this but just in case it is a bug I share it. When you hover a banner with unused banners around, you can see the complete image:

![image](https://cloud.githubusercontent.com/assets/11770760/25362518/a8768252-2954-11e7-81e4-974903e3fab5.png)

![image](https://cloud.githubusercontent.com/assets/11770760/25362524/b9c7c1a6-2954-11e7-9a2b-80c493f37492.png)

**Comment by Kapiainen** [comment]
> Hello again, I found that if Zoom In hover animation is enabled, when you hide a game the banner still appearing until you stop on hover it. With jiggle that doesn't happen, or with that option disabled.

Fixed in the upcoming version.

> Other issue, shake hover animation is not working I think, at least I don't see any change in the banner.

Fixed in the upcoming version.

> And finally, in Zoom in hover animation I don't know if this a bug or it works like it has to work, I don't see much problem with this but just in case it is a bug I share it. When you hover a banner with unused banners around, you can see the complete image:

That is definitely a bug. The new way of handling slot animations works by:
- Using a separate image meter, which is drawn below all slot meters, for animations to ensure that the animated banner does not end up covering the banners of slots around it.
- Using a shape meter, which is drawn between the actual slot meters and the animation meter, to act as a mask so that the animated banner does not end up covering empty slots or slots without banners.
So the behavior that can be seen in your screenshots should not be happening. I tried reproducing the issue, but I have not been able to do so yet.

![lauhdutin-issue70-repro](https://cloud.githubusercontent.com/assets/7756625/25368253/d5bfccda-2983-11e7-821e-0c88ba42bc4f.png)

**Comment by Kapiainen** [comment]
Could you check what the value of the *SlotBackgroundColor* variable is when you have Lauhdutin running? Just go to Rainmeter's *Log* window, click on the *Skins* tab, and select the correct skin. You should see a list of measures and variables on the right-hand side of the window. You should see something like `slotbackgroundcolor 0,0,0,255`. I suspect the alpha value (fourth number in my example) is not 255 in your screenshots.

**Comment by Kapiainen** [comment]
Beta 4 addresses the last issue that you brought up. The Python script that builds a part of the skin was set to use a legacy setting (from versions prior to 2.0.0), but the color is hard coded into the script for now and will ignore the value that may have been left behind in the settings file.

**Comment by BanCrash** [comment]
Well, that was fast, thanks you one more time!! 

About your edit of the perfomance you're right, and I think the problem is with the images. Because I set a grid of 6x7 with 310x145 slot size and it works laggy, but the same grid with 155x73 slot size works like a charm. The games are the same, the only thing changes are the images size, so I think the problem is that.
