### ISSUE TITLE
Minor issues

### ISSUE THREAD

**Issue by BanCrash** [Kapiainen/Lauhdutin#71]
Two minor issues I found in the last beta 4:

-When I start unhiding games in the previous versions the skin go automatically to hidden games. In this version that doesn't happen. I am not sure if it is the way to work, but just in case I let here. Also, If I have hidden:true filter active and I start hidden games, it doesn't go to games unhidden neither.

-A minor visual issue. When I set the default size width and height the slots are not aligned for a little bit:

![image](https://cloud.githubusercontent.com/assets/11770760/25381728/26e0306a-29b5-11e7-9ffc-b6de17a1ebfa.png)

It isn't anything important in any case.

**Comment by Kapiainen** [comment]
> When I start unhiding games in the previous versions the skin go automatically to hidden games. In this version that doesn't happen. I am not sure if it is the way to work, but just in case I let here. Also, If I have hidden:true filter active and I start hidden games, it doesn't go to games unhidden neither.

I refactored the code relating to filtering during the recent GUI overhaul and during that process I figured it would be best to not suddenly throw the user to another screen. My thought process at the time was that perhaps the user had applied some filters to find a specific set of games, which may have included hidden ones as well. One solution could be to check if any of the games in the current set of filtered games are hidden, if not then show all hidden games. Thoughts on that solution?

> A minor visual issue. When I set the default size width and height the slots are not aligned for a little bit:

This is due to the Python script, which is responsible for building a part of the skin, doing some float division and then doing some rounding when converting the result to an integer. The slot meters (i.e. text and banners) are using relative positioning 1) to make it easier to do animations involving the entire skin, and 2) to offload as much of the logic as possible to the C/C++ parts of Rainmeter instead of doing everything in Lua and telling Rainmeter what to do. I'll change the defaults to even numbers that don't have this issue (i.e. numbers that can be divided by 2 without leaving a remainder). It is best to use something like 320 or 322 instead of 361 or 363. Technically all of the texts are also be slightly off-center when using odd numbers.

**Comment by BanCrash** [comment]
About that last issue I think the problem is that any row add 1 pixel extra, because each banner have the black line of the previous banner, and one added. I don't explain very well, but I think in the image this will be clarifying:

![image](https://cloud.githubusercontent.com/assets/11770760/25389475/0c16d3e4-29d1-11e7-9fc7-b4b986ffcc63.png)

EDIT: While I am writing this message you write a answer.

About the first answer: I think that could be a great solution. Just to clarify, the idea is when are hidden games on the current filter show only the hidden games that are on that filter, excluding games that aren't hidden (or vice versa in case that are using unhidder), and if there is no one show all hidden games, no? I want to clarify that because other option I think is to show all games of that filter, hidden or not, if there is only one hidden game in that filter, but I think this is unnecesary because you can't hide a game that are already hide, so I think is better only show hidden games that have that filter.

About the second answer I write more information in this post, I don't know if the answer is the same so just in case I let that part write.

**Comment by Kapiainen** [comment]
Both issues should be fixed now in beta 5. Slots should be aligned properly for all possible values of slot widths and heights. Toggling the hide/unhide games state now initially tries to remove all hidden/visible games from the current list of filtered games and if there are no games left, then shows all visible/hidden games.

**Comment by BanCrash** [comment]
Perfect, that's cool, thanks you so much again!!
